import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.scss'
import { ReactNode } from 'react'
import {Toaster} from "@/components/ui/toaster";
import NextTopLoader from "nextjs-toploader";

const nunito = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ru">
      <body className={`${ nunito.variable }`}>
        <NextTopLoader />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
